apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #kubernetes.io/ingress.class: ingress-internal
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false" 
spec:
  rules:
  - host: {{ .Release.Namespace }}.{{.Values.cluster.fqdn}}
    http:
      paths:
      - backend:
          service: 
            name: "basic-app-service"
            port: 
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Release.Name }}.{{.Values.cluster.fqdn}}
    secretName: basic-app-tls-secret

