apiVersion: v1
kind: Service
metadata:
  labels:
    app: basic-app-service
  name: basic-app-service
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    {{ toYaml .Values.labels }}